name: 'silverbackltd-build-action'
author: 'Silverback Ltd.'
description: 'A GitHub Action to build docker images for a silverback repository and push to a container registry'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  push:
    description: 'Push the image to ghcr'
    required: false
    default: 'false'

outpus:
  built_images:
    description: 'List of Docker images that were built and pushed.'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "REGISTRY=" >> $GITHUB_ENV
        echo "IMAGE_NAME=${{ github.repository }}"
        echo "TARGET_DIR=$GITHUB_WORKSPACE/.silverback-images"
        echo "DOCKERFILE_PATTERN=Dockerfile.*"
        echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
        echo "GITHUB_REF=${{ github.ref }}"

    - name: Check if Directory Exists
      id: check_dir
      run: |
        if [ -d "${{ env.TARGET_DIR }}" ]; then
          echo "Directory exists."
          echo "directory_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Directory does not exist. Creating..."
          mkdir -p "${{ env.TARGET_DIR }}"
          echo "directory_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Set Lowercase Repository Owner
      id: lowercase_owner
      run: |
        LOWERCASE_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        echo "LOWERCASE_OWNER=$LOWERCASE_OWNER" >> $GITHUB_ENV

    - name: Generate Files
      id: gen_files
      if: steps.check_dir.outputs.directory_exists == 'false'
      run: |
        pip install silverback
        silverback build --generate

    - name: Verify Dockerfiles Exist
      run: |
        if [ ! -d "${{ env.TARGET_DIR }}" ]; then
          echo "Directory '${{ env.TARGET_DIR }}' does not exist. Exiting."
          exit 1
        fi

    - name: Log into GitHub Container Registry
      if: ${{ inputs.push }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      run: |
        # Find all Dockerfiles matching the pattern
        dockerfiles=$(find "${{ env.TARGET_DIR }}" -type f -name "${{ env.DOCKERFILE_PATTERN }}" | sort)
        echo "Found Dockerfiles:"
        echo "${dockerfiles}"

        dockerfile_array=()
        for df in $dockerfiles; do
          name=$(basename "$df" | sed 's/Dockerfile\.//')
          tag=${{ env.REGISTRY }}/${{ env.LOWERCASE_OWNER }}/${name}:latest
          docker build -t "$tag" -f "$df" .
          if [[ ${{ inputs.push }} ]]; then
            docker push "$tag"
          fi
        done
