name: Test Container Images

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test-root:
    name: Run action with `bot.py`
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: set up test
        run: curl https://raw.githubusercontent.com/ApeWorX/silverback/refs/heads/main/example.py > bot.py
        shell: bash

      - name: run action
        uses: ./

  test-folder:
    name: Run action with `bot/`
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: set up test
        run: |
          mkdir bot
          curl https://raw.githubusercontent.com/ApeWorX/silverback/refs/heads/main/example.py > bot/__init__.py
        shell: bash

      - name: run action
        uses: ./

  test-folder-multiple:
    name: Run action with `bots/`
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: set up test
        run: |
          mkdir bots
          curl https://raw.githubusercontent.com/ApeWorX/silverback/refs/heads/main/example.py > bots/example1.py
          cp bots/example1.py bots/example2.py
        shell: bash

      - name: run action
        uses: ./

  test-missing-file:
    name: Run action without a file
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - id: must-fail
        name: run action
        continue-on-error: true
        uses: ./

      - name: check result
        if: steps.must-fail.outcome == 'success'
        run: exit 1


