name: Test Container Images

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test-action:
    name: Run action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: checkout example silverback package
        uses: actions/checkout@v4
        with:
          repository: ApeAcademy/erc-4626
          path: erc-4626

      - name: show cd
        run: |
          cp -r erc-4626/* .
        shell: bash

      - name: silverback build
        uses: ./


