name: Test Container Images

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test-action:
    name: Run action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: silverback build
        uses: ./


