name: Test Container Images

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test-action:
    name: Run action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Add required files
        run: |
          touch ape-config.yaml
          touch requirements.txt

      - name: silverback build
        uses: ./
        with:
          push: false
          tag: latest
          password: ${{ secrets.GITHUB_TOKEN }}


